import { AppShell } from "@/components/AppShell";
import { StrategyLibrary } from "@/components/StrategyLibrary";

export default function StrategiesPage() {
  return (
    <AppShell>
      <div className="page-heading">
        <span>Strategy library</span>
        <h1>Save paper-tested rules</h1>
        <p>V1 strategies are simple rules that can be generated by Scout or saved manually.</p>
      </div>
      <StrategyLibrary />
    </AppShell>
  );
}
